#!/bin/bash

##############################
# GTK launcher specific part #
##############################

if [ "$DESKTOP_LAUNCHER_WAYLAND_AVAILABLE" = "true" ]; then
  export GDK_BACKEND="wayland"
  export CLUTTER_BACKEND="wayland"
  # Does not hurt to specify this as well, just in case
  export QT_QPA_PLATFORM=wayland-egl
fi

# ibus and fcitx integration
if [ "$DESKTOP_LAUNCHER_NEEDS_UPDATE" = "true" ]; then
  rm -rf "$GTK_IM_MODULE_DIR"
  mkdir -p "$GTK_IM_MODULE_DIR"
  if [ -x "$RUNTIME/usr/lib/$ARCH/libgtk-3-0/gtk-query-immodules-3.0" ]; then
    ln -s "$RUNTIME/usr/lib/$ARCH/gtk-3.0/3.0.0/immodules"/*.so "$GTK_IM_MODULE_DIR"
    "$RUNTIME/usr/lib/$ARCH/libgtk-3-0/gtk-query-immodules-3.0" > "$GTK_IM_MODULE_FILE"
  elif [ -x "$RUNTIME/usr/lib/$ARCH/libgtk2.0-0/gtk-query-immodules-2.0" ]; then
    ln -s "$RUNTIME/usr/lib/$ARCH/gtk-2.0/2.10.0/immodules"/*.so "$GTK_IM_MODULE_DIR"
    "$RUNTIME/usr/lib/$ARCH/libgtk2.0-0/gtk-query-immodules-2.0" > "$GTK_IM_MODULE_FILE"
  fi
fi

exec "$@"
