#!/bin/bash

if [ "$PLATFORM_PLUG" == "kf6-core24" ]; then

set -- "${SNAP}/kf6/command-chain/hooks-configure-fonts" "$@"
# shellcheck source=/dev/null
source "${SNAP}/snap/command-chain/run"

if [ "$PLATFORM_PLUG" == "kde-qt6-core24" ]; then

set -- "${SNAP}/qt6/command-chain/hooks-configure-fonts" "$@"
# shellcheck source=/dev/null
source "${SNAP}/snap/command-chain/run"

elif [ "$PLATFORM_PLUG" == "kf5-core24" ]; then

set -- "${SNAP}/kf5/command-chain/hooks-configure-fonts" "$@"
# shellcheck source=/dev/null
source "${SNAP}/snap/command-chain/run"

fi
