#!/bin/bash

if [ -z "$1" ]; then
  echo "run <command>"
  exit 1
fi

if [ -z "${SNAP}" ]; then
  echo "Not running inside a snap context: SNAP not declared"
  exit
fi


if [ ! -f "$1" ]; then
  echo "Content snap command-chain for $1 not found: ensure slot is connected"
  exit
fi

# emulate "exec $@" using "source"
# have to disable "unused variables" because checkshell doesn't know that $BASH_ARGV0 is $0
# shellcheck disable=SC2034  # Unused variables left for readability
BASH_ARGV0=$1
shift
# shellcheck source=/dev/null
source "$0"
