#!/bin/sh

set -e
export ARCH_PATH=""
if [ $SNAP_ARCH == "armhf" ]; then
    ARCH_PATH=armv7l-linux-eabihf
else
    ARCH_PATH=x86_64-linux
fi
export PATH="$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH"
export LD_LIBRARY_PATH=$SNAP/lib:$SNAP/usr/lib/$(uname -p)-linux-gnu/:$LD_LIBRARY_PATH:$SNAP_LIBRARY_PATH

export RUBYDIR=$SNAP/lib/ruby
export RUBYLIB=$RUBYDIR/2.3.0
RUBYLIB=$RUBYLIB/$ARCH_PATH/:$RUBYLIB
export GEM_HOME=$RUBYDIR/gems/2.3.0
export GEM_PATH=$RUBYDIR/gems/2.3.0

exec "$SNAP/bin/ruby" "$SNAP/ruby-hello.rb" "$@"
