#!/bin/bash

set -e

export RUBYPATH=$SNAP/bin
export RUBYLIB=$SNAP/lib/ruby/2.3.0/:$SNAP/lib/ruby/2.3.0/x86_64-linux/
export GEM_HOME=$SNAP/lib/ruby/gems
export GEM_PATH=$SNAP/lib/ruby/gems

exec ruby -e "puts 'Ruby says, Hello snapcraft.';"
