#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

apt-get -y update
apt-get -y --no-install-recommends install jq

"${DIR}/../build.sh" "${DOCKER_TAG}" "${DOCKER_REPO}" "linux/amd64,linux/arm64,linux/arm/v7"
