#!/bin/bash -e

KF5="$SNAP/kf5"
export KF5

if [ ! -d "$KF5/usr" ]; then
  source /etc/os-release
  runtime="kde-frameworks-5"
  slot="kde-frameworks-5:kde-frameworks-5-slot"
  if [ "$VERSION" == "18" ]; then
    runtime="kde-frameworks-5-core18"
    slot="kde-frameworks-5-core18:kde-frameworks-5-core18-slot"
  fi

  echo "You need to connect this snap to the $runtime snap."
  echo ""
  echo "You can do this with those commands:"
  echo "snap install $runtime"
  echo "snap refresh $runtime"
  echo "snap connect $SNAP_NAME:kde-frameworks-5-plug $slot"
  exit 1
fi

exec "$@"
