#!/bin/sh

set -e
set -x

# installation pathes are based of CATALINA_HOME
export CATALINA_HOME="$SNAP_APP_PATH"
# writable pathes are based of CATALINA_BASE
export CATALINA_BASE="$SNAP_APP_DATA_PATH"

# create runtime data
mkdir -p "$CATALINA_BASE/logs"
mkdir -p "$CATALINA_BASE/temp"
if ! [ -d $CATALINA_BASE/conf ]; then
    cp -dr $CATALINA_HOME/conf $CATALINA_BASE
fi

$CATALINA_HOME/bin/startup.sh

