#!/bin/bash -e

###############################
# Mark update and exec binary #
###############################

if [ "$SNAP_DESKTOP_COMPONENTS_NEED_UPDATE" = true ]; then
  echo "SNAP_DESKTOP_LAST_REVISION=$SNAP_REVISION" > "$SNAP_USER_DATA/.last_revision"
fi

if [ -n "$SNAP_DESKTOP_DEBUG" ]; then
  echo "desktop-launch elapsed time: " "$(date +%s.%N --date="$SNAP_DESKTOP_START seconds ago")"
  echo "Now running: exec $*"
fi

exec "$@"
