#!/bin/bash

###############################
# Mark update and exec binary #
###############################

[ $DESKTOP_LAUNCHER_NEEDS_UPDATE = true ] && echo "SNAP_DESKTOP_LAST_REVISION=$SNAP_REVISION" > $SNAP_USER_DATA/.last_revision
unset DESKTOP_LAUNCHER_NEEDS_UPDATE

if [ -n "$SNAP_DESKTOP_DEBUG" ]; then
  echo "desktop-launch elapsed time: " $(date +%s.%N --date="$START seconds ago") 
  echo "Now running: exec $@"
fi

exec "$@"
