#!/bin/bash -e

###############################
# Mark update and exec binary #
###############################

if [ "$SNAP_DESKTOP_COMPONENTS_NEED_UPDATE" = "true" ]; then
  echo "SNAP_DESKTOP_LAST_REVISION=$SNAP_REVISION" > "$SNAP_USER_DATA/.last_revision"
fi

unset SNAP_DESKTOP_COMPONENTS_NEED_UPDATE

exec "$@"
