#!/bin/sh
set -e

cd "$SNAP_APP_DATA_PATH"

[ -f configuration ] && interval=$(sed -n 's/.*interval: `\([0-9.]\+\).*/\1/p' configuration)

[ -z "$interval" ] && interval=10

echo "Snapping every $interval seconds"

golang-static-http &

while :; do
    fswebcam shot.jpeg
    sleep $interval
done
