#!/bin/bash
set -e
set -u

LIBRARY_DIR=$SNAP_APP_PATH/usr/
ARCHITECTURE=x86_64-linux-gnu

export XDG_CONFIG_DIRS=$LIBRARY_DIR/xdg:/etc/xdg
export QTCHOOSER_NO_GLOBAL_DIR=1
export QT_QPA_PLATFORM=ubuntumirclient
export QT_PLUGIN_PATH=$LIBRARY_DIR/lib/$ARCHITECTURE/qt5/plugins
export QML2_IMPORT_PATH=$$LIBRARY_DIR/lib/$ARCHITECTURE/qt5/qml

export MIR_SOCKET=/run/mir_socket
export MIR_CLIENT_PLATFORM_PATH=$LIBRARY_DIR/lib/$ARCHITECTURE/mir/client-platform

export LD_LIBRARY_PATH=$LIBRARY_DIR/lib/$ARCHITECTURE/mesa-egl:$LIBRARY_DIR/lib/$ARCHITECTURE/mesa:$LIBRARY_DIR/lib/$ARCHITECTURE:$LD_LIBRARY_PATH

$LIBRARY_DIR/bin/$ARCHITECTURE/qmlscene

