#!/bin/bash

GPU_WRAPPER="${SNAP}/gpu-2404/bin/gpu-2404-provider-wrapper"

if [ -z "$1" ]; then
  echo "Usage: gpu-2404-wrapper <command>"
  exit 1
fi

if [ -z "${SNAP}" ]; then
  echo "Not running inside a snap context: SNAP not declared"
  exit 2
fi

if [ ! -f "${GPU_WRAPPER}" ]; then
  echo "Content snap command-chain for $1 not found: ensure slot is connected"
  exit 3
fi

# emulate "exec $@" using "source"
# have to disable "unused variables" because checkshell doesn't know that $BASH_ARGV0 is $0
# shellcheck disable=SC2034  # Unused variables left for readability
BASH_ARGV0="${GPU_WRAPPER}"
# shellcheck source=/dev/null
source "${GPU_WRAPPER}"
