name: Update Copilot Instructions
on:
  schedule:
    - cron: "0 9 * * 1" # Run every Monday at 09:00 UTC
  workflow_dispatch:

jobs:
  check-update:
    # Pinned to @main to get the latest logic, but the content version is controlled by .github/copilot-collections.yaml
    uses: canonical/copilot-collections/.github/workflows/auto_update_collections.yaml@main
    secrets: inherit
