name: Release
on:
  push:
    tags:
      # These tags should be protected, remember to enable the rule:
      # https://github.com/canonical/starbase/settings/tag_protection
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  source-wheel:
    runs-on: [self-hosted]
    permissions:
      contents: read
    steps:
      - name: Install uv
        run: |
          sudo snap install --classic astral-uv
          sudo apt --yes install python3-venv
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Fetch tag annotations
        run: |
          # Note: we fetch the tags here instead of using actions/checkout's "fetch-tags"
          # because of https://github.com/actions/checkout/issues/1467
          git fetch --force --tags --depth 1
          git describe --dirty --long --match '[0-9]*.[0-9]*.[0-9]*' --exclude '*[^0-9.]*'
      - name: Build packages
        run: |
          uv venv --no-managed-python
          uv pip install build twine
          uv run -m build
          uv run twine check dist/*
      - name: Upload pypi packages artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: pypi-packages
          path: dist/
  pypi:
    needs: ["source-wheel"]
    runs-on: [self-hosted, amd64]
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - name: Get packages
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: pypi-packages
          path: dist/
      - name: Publish to pypi
        # Note: this action uses PyPI's support for Trusted Publishers
        # It needs a configuration on the PyPI project - see:
        # https://docs.pypi.org/trusted-publishers/adding-a-publisher/#github-actions
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # release/v1
  github-release:
    needs: ["source-wheel"]
    runs-on: [self-hosted]
    permissions:
      contents: write
    steps:
      - name: Get pypi artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: pypi-packages
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ github.ref_name }}
        run: gh release create "$RELEASE_TAG" --generate-notes -- *.whl *.tar.gz
