name: TICS
on:
  push:
    branches:
      - "main"
      # to easy test changes to the workflow
      - "tiobe"

jobs:
  TICS:
    uses: canonical/starflow/.github/workflows/tics.yaml@CRAFT-4322-migrate-tics-workflow-to-starflow
    with:
      project: "snapcraft"
    secrets: inherit
