name: TICS
on:
  push:
    branches:
      - "main"
      # For troubleshooting
      - "work/tiobe**"

jobs:
  TICS:
    permissions:
      contents: read
    uses: canonical/starflow/.github/workflows/tics.yaml@main # zizmor: ignore[unpinned-uses] starflow workflows are exempt from hash-pinning
    with:
      project: "snapcraft"
    secrets: inherit
